# Generated by Django 5.1.3 on 2025-01-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_str', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_deadline', models.DateTimeField(blank=True, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('uses_remaining', models.IntegerField(blank=True, null=True)),
                ('maximum_uses', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_image', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_formatted', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('students', models.IntegerField(blank=True, null=True)),
                ('courses', models.IntegerField(blank=True, null=True)),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_link', models.URLField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('video_content_length', models.CharField(blank=True, max_length=50, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_ratings', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('what_you_will_learn', models.JSONField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('big_description', models.TextField(blank=True, null=True)),
                ('who_this_course_is_for', models.TextField(blank=True, null=True)),
                ('coupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coupon')),
                ('reviews', models.ManyToManyField(blank=True, to='api.coursereview')),
                ('instructor', models.ManyToManyField(blank=True, to='api.instructor')),
            ],
        ),
    ]
