# Generated by Django 5.1.3 on 2025-02-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursedetail",
            name="reviews",
        ),
        migrations.RemoveField(
            model_name="coursedetail",
            name="instructor",
        ),
        migrations.DeleteModel(
            name="CourseReview",
        ),
        migrations.DeleteModel(
            name="Instructor",
        ),
    ]
