# Generated by Django 5.1.3 on 2025-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_coursedetail_reviews_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_deadline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="expires_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coursedetail",
            name="what_you_will_learn",
            field=models.TextField(blank=True, null=True),
        ),
    ]
