# Generated by Django 5.1.3 on 2025-02-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_coupon_is_available_alter_coupon_discount_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coursedetail",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.coupon",
            ),
        ),
    ]
