# Generated by Django 5.1.3 on 2025-02-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_coupon_updated_at_alter_coursedetail_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetail",
            name="coupon",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.coupon",
            ),
        ),
    ]
