# Generated by Django 5.1.3 on 2025-02-11 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_coursedetail_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
