# Generated by Django 5.1.3 on 2025-02-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_coursedetail_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="coupon_str",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="coursedetail",
            name="coupon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.coupon"
            ),
        ),
    ]
